ARG DEBIAN_FRONTEND=noninteractive
ARG BASE=ghcr.io/coqui-ai/tts:dbf1a08a0d4e47fdad6172e433eeb34bc6b13b4e
FROM ${BASE}

RUN pip3 install --no-cache-dir sagemaker

# Copy TTS repository contents:
WORKDIR /root
COPY . /root

ENV PATH="/root:${PATH}"

RUN make install