ARG DEBIAN_FRONTEND=noninteractive
ARG BASE=nvidia/cuda:11.8.0-base-ubuntu22.04
FROM ${BASE}

RUN apt-get update # && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends gcc g++ make python3 python3-dev python3-pip python3-venv python3-wheel espeak-ng libsndfile1-dev && rm -rf /var/lib/apt/lists/*
RUN pip3 install llvmlite --ignore-installed

# Install Dependencies:
RUN pip3 install torch==2.2.0 torchaudio==2.2.0 --extra-index-url https://download.pytorch.org/whl/cu118
RUN pip3 install --no-cache-dir sagemaker deepspeed==0.10.3

RUN rm -rf /root/.cache/pip

# Copy TTS repository contents:
WORKDIR /root
COPY . /root

ENV PATH="/root:${PATH}"

RUN make install

ENTRYPOINT /root/serve